// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT2DyQ-wUsdI6tWMub0rZXXs_q-YCiIss',
    appId: '1:278762312332:web:ead41a5259b428349261a9',
    messagingSenderId: '278762312332',
    projectId: 'trash-dash-demo',
    authDomain: 'trash-dash-demo.firebaseapp.com',
    storageBucket: 'trash-dash-demo.firebasestorage.app',
    measurementId: 'G-NBKQLT0D49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnASlw1bdXoMwAx-3z-9MckCXDBs1_S1E',
    appId: '1:278762312332:android:a97f0cf7c450b7429261a9',
    messagingSenderId: '278762312332',
    projectId: 'trash-dash-demo',
    storageBucket: 'trash-dash-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIdKwUjbSHaRqMGt99JdkL049i2-A9Ayo',
    appId: '1:278762312332:ios:807d020f9c3fa3cb9261a9',
    messagingSenderId: '278762312332',
    projectId: 'trash-dash-demo',
    storageBucket: 'trash-dash-demo.firebasestorage.app',
    iosBundleId: 'com.example.trashDashDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIdKwUjbSHaRqMGt99JdkL049i2-A9Ayo',
    appId: '1:278762312332:ios:807d020f9c3fa3cb9261a9',
    messagingSenderId: '278762312332',
    projectId: 'trash-dash-demo',
    storageBucket: 'trash-dash-demo.firebasestorage.app',
    iosBundleId: 'com.example.trashDashDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT2DyQ-wUsdI6tWMub0rZXXs_q-YCiIss',
    appId: '1:278762312332:web:34f6a04f78ba6f8c9261a9',
    messagingSenderId: '278762312332',
    projectId: 'trash-dash-demo',
    authDomain: 'trash-dash-demo.firebaseapp.com',
    storageBucket: 'trash-dash-demo.firebasestorage.app',
    measurementId: 'G-GPLTWTM8PY',
  );

}